name: Auto Deploy to Ubuntu Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Deploy to Ubuntu via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: 192.168.8.10
        username: euch997
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          cd /var/www/html
          git pull origin main
          echo "✅ Deploy sukses ke server!"
